export const M_TOKEN =
  'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3MjRiZWVmNDY3ZTU5NDlkMGYwY2ViNmNkMmFlMjUxNiIsInN1YiI6IjY2MmY0NjY0OGE4OGIyMDEyYWNlYmJjNCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.hBlkp6NRtm31DUzNUdQca8SurVrVVShzZAlK_kFj2hM';
export const BASE_URL = 'https://api.themoviedb.org/3';
